# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eurekabootcamp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_62f5281a002b4079a87f2c063af663c7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b5acf7a65ec64f5ebb4b561c2054afe0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_62f5281a002b4079a87f2c063af663c7 }}/jhctdev/eureka-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eurekabootcamp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_edc0480164a049c586f314cc8211691c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_62f5281a002b4079a87f2c063af663c7 }}/jhctdev/eureka-server:${{ github.sha }}'